//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlWork02
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", 
            "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public TechObject()
        {
            this.MaintenanceWorks = new HashSet<MaintenanceWorks>();
        }

        public TechObject(string name, string productionDate, 
                          string shippingDate, int warrantyPeriod)
        {
            this.Id = System.Guid.NewGuid();
            this.Name = name;
            this.ProductionDate = productionDate;
            this.ShippingDate = shippingDate;
            this.WarrantyPeriod = warrantyPeriod;
        }

        public System.Guid Id { get; set; }
        public string ProductionDate { get; set; }
        public string ShippingDate { get; set; }
        public int WarrantyPeriod { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", 
            "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<MaintenanceWorks> MaintenanceWorks { get; set; }
    }
}
